### ISSUE TITLE
Services does not work

### ISSUE THREAD

**Issue by FeromonDE** [rsnodgrass/hass-lunos#4]
When I am trying to set the summer ventilation off/on or the filter reset function on my e2 its not working.
action:
  - service: lunos.lunos_clear_filter_reminder
    data:
      entity_id: fan.wozivorne

and in the log:

`Unable to find referenced entities fan.wozivorne`

**Comment by Henry-Sir** [comment]
Same here.

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 20:13:38 (1 occurrences)
Last logged: 20:13:38

Unable to find referenced entities fan.lunos_luftung
```

Currently I have created a script to perform a reset. It is the same thing that the service does.  (see fan.py - from line 380)

```
alias: Lunos Luftung - Reset Filter 
sequence:
  - service: scene.create
    data:
      scene_id: lunos_lftung_filter_clear_revert
      snapshot_entities: switch.shelly_shuni_1_98cdac24fff4_1
  - service: switch.turn_off
    target:
      entity_id: switch.shelly_shuni_1_98cdac24fff4_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - service: switch.turn_on
    target:
      entity_id: switch.shelly_shuni_1_98cdac24fff4_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - service: switch.turn_off
    target:
      entity_id: switch.shelly_shuni_1_98cdac24fff4_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - service: switch.turn_on
    target:
      entity_id: switch.shelly_shuni_1_98cdac24fff4_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - service: switch.turn_off
    target:
      entity_id: switch.shelly_shuni_1_98cdac24fff4_1
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - service: switch.turn_on
    target:
      entity_id: switch.shelly_shuni_1_98cdac24fff4_1
  - service: scene.turn_on
    target:
      entity_id: scene.lunos_lftung_filter_clear_revert
mode: single
```
